/*
 * Birge · тексты оболочки R01 на русском и казахском (раунд 14).
 *
 * Источник истины для переводов — словари R11 (web/civic/i18n/ru.json, kk.json). Пока ключей shell.* там нет,
 * оболочка берёт текст отсюда: BirgeShell.t(key) сначала ищет в словаре R11, затем здесь (birge.js).
 * Когда R11 перенесёт ключи к себе (INTEGRATION.txt R01 §5), этот файл можно будет сократить.
 * Казахский — предложение R01, вычитывает R11 и владелец. Параметры — {name}, числа — {n}.
 *
 * Работает и в Node (module.exports) — для тестов explore.js без браузера.
 */
(function (root) {
  "use strict";
  const TEXT = {
    ru: {
      // шапка и общие
      "shell.brand.tagline": "Город и жители вместе",
      "shell.title": "Birge · Астана",
      "shell.nav.label": "Разделы",
      "shell.map.label": "Карта Астаны",
      "shell.root.label": "Городская платформа Астаны",
      "common.nav.map": "Карта",
      "common.nav.day": "Картина дня",
      "common.nav.menu": "Меню",
      "common.nav.mine": "Мои обращения",
      "common.action.skip_to_main": "Перейти к главной кнопке",
      "common.lang.label": "Язык интерфейса",
      "common.lang.ru": "РУС",
      "common.lang.kk": "ҚАЗ",
      "common.role.label": "Чей вид",
      "common.role.akimat": "Акимат",
      "common.role.resident": "Житель",
      // B3: кнопка каталога 3D-проектов (ключи R11 proposal.catalog.title, common.action.close) — запасной текст
      "proposal.catalog.title": "Что построить?",
      "common.action.close": "Закрыть",
      "common.action.retry": "Повторить",
      "common.search.clear": "Очистить поиск",
      "akim.title": "Картина дня",
      // «Картина дня» без модуля R08
      "shell.day.soon_title": "Картина дня скоро появится",
      "shell.day.soon_text": "Здесь будет сводка за день: темы обращений, районы, горячие места, просрочки и объекты с отставанием.",
      "shell.day.back": "Вернуться к карте",
      "shell.day.error_title": "Картину дня не удалось открыть",
      "shell.day.error_text": "Попробуйте ещё раз через минуту.",
      // панель карты
      "shell.sheet.expand": "Развернуть панель",
      "shell.sheet.collapse": "Свернуть панель",
      "shell.panel.eyebrow": "Астана · городские работы и события",
      "shell.panel.title": "Что меняется в городе",
      "shell.panel.note": "Показаны только опубликованные записи. У каждой карточки — источник, тип сведений и история сроков.",
      "shell.feedback.label": "Сообщение жителя",
      "shell.feedback.title": "Сообщить о проблеме или предложении",
      "shell.feedback.close": "Закрыть форму",
      "shell.assistant.label": "Вопрос по объекту",
      "shell.staff.open": "Для сотрудников",
      "shell.scenarios.open": "Сравнить ограничения",
      "shell.moderation.open": "Сообщения жителей",
      "shell.editor.title": "Кабинет сотрудника",
      "shell.editor.close": "Закрыть кабинет",
      "shell.moderation.title": "Сообщения жителей",
      "shell.moderation.close": "Закрыть сообщения",
      "shell.scenarios.title": "Сравнение ограничений",
      "shell.scenarios.close": "Закрыть сравнение",
      // состояния
      "shell.module.missing": "Эта часть пока не загрузилась. Обновите страницу или вернитесь позже.",
      "shell.module.failed": "Эта часть не запустилась. Обновите страницу или вернитесь позже.",
      "shell.state.no_server": "Нет связи с сервером. Проверьте, что приложение запущено, и обновите страницу.",
      "shell.state.no_store": "Записи о работах сейчас недоступны: карта пока пуста.",
      "shell.feedback.unavailable": "Отправка сообщений сейчас недоступна.",
      "shell.moderation.failed": "Список сообщений не открылся. Обновите страницу.",
      "shell.tool.click_hint": "Пока открыт инструмент на карте, нажатие не открывает карточки объектов.",
      // ошибки запросов (видны в модулях)
      "shell.api.failed": "Запрос не выполнен.",
      "shell.api.timeout": "Сервер не ответил вовремя. Повторите попытку.",
      "shell.api.network": "Нет связи с сервером приложения.",
      "shell.api.bad_response": "Сервер вернул нечитаемый ответ.",
      "shell.api.unauthenticated": "Войдите как сотрудник, чтобы продолжить.",
      // строка «что показано на карте»
      "shell.view.city": "Обзор: вся Астана",
      "shell.view.object": "Открыта запись: {title}",
      "shell.view.object_untitled": "Открыта запись",
      "shell.view.district": "Район {name} (граница OSM)",
      "shell.view.street": "Улица: {name}",
      "shell.view.objects": "Все опубликованные записи на карте",
      "shell.view.registry_empty": "{label} · реестр пуст",
      "shell.view.in_frame": "{label} · записей в кадре: {n}",
      "shell.view.none_in_frame": "{label} · в кадре опубликованных записей нет (это не значит, что работ нет)",
      "shell.objects.none": "В реестре пока нет опубликованных записей.",
      "shell.objects.no_coords": "Нет объектов с координатами для выбранных фильтров.",
      // навигация по городу (explore.js)
      "shell.explore.label": "Навигация по Астане",
      "shell.explore.area": "Территория",
      "shell.explore.district_label": "Район Астаны",
      "shell.explore.all_city": "Вся Астана",
      "shell.explore.to_objects": "К объектам",
      "shell.explore.layers": "Слои",
      "shell.explore.layers_label": "Покрытие и слои карты",
      "shell.explore.district_borders": "Границы районов",
      "shell.explore.coverage": "Карта доступна по всей Астане. Пустое место означает отсутствие опубликованных записей, а не отсутствие работ.",
      "shell.explore.borders_source": "Границы: OpenStreetMap, снимок 23.09.2026. Это общественная карта, не кадастровые границы.",
      "shell.explore.street_placeholder": "Улица Астаны",
      "shell.explore.street_label": "Найти улицу в Астане",
      "shell.explore.find": "Найти",
      "shell.explore.streets_label": "Улицы Астаны",
      "shell.explore.loading": "Загружаем список улиц…",
      "shell.explore.street_hint": "Названия улиц из OpenStreetMap. Поиск по улицам, без номеров домов.",
      "shell.explore.street_hint_date": "Названия улиц из OpenStreetMap на {date}. Поиск по улицам, без номеров домов.",
      "shell.explore.index_error": "Поиск улиц недоступен: список улиц не загрузился. Выберите район или повторите.",
      "shell.explore.pin_title": "Примерное место: центр участка улицы по OpenStreetMap",
      "shell.explore.more": "Ещё {n} — уточните название",
      "shell.explore.not_found": "Улица не найдена в снимке OpenStreetMap. Проверьте написание или выберите район.",
      "shell.explore.found_ambiguous": "Найдено вариантов: {n}. Одноимённые улицы подписаны районом.",
      "shell.explore.found_pick": "Найдено вариантов: {n}. Выберите стрелками и Enter или касанием.",
      "shell.explore.chosen": "Показана улица: {name} ({place}). Список записей — по видимой части карты.",
      "shell.explore.count": "Опубликовано записей: {n}. Из них демонстрационных: {demo}.",
      "shell.explore.registry_empty": "Реестр пуст: опубликованных записей пока нет. Пустая карта не значит, что в городе нет работ.",
      "district.name": "район {name}",
      "district.esil": "Есиль",
      "district.almaty": "Алматы",
      "district.saryarka": "Сарыарка",
      "district.baikonur": "Байконур",
      "district.nura": "Нура",
      "district.saraishyk": "Сарайшык",
      "shell.explore.place_outside": "окрестности, вне границ районов",
      "shell.explore.place_part": "{place} · участок {i} из {n}",
    },
    kk: {
      "shell.brand.tagline": "Қала мен тұрғындар бірге",
      "shell.title": "Birge · Астана",
      "shell.nav.label": "Бөлімдер",
      "shell.map.label": "Астана картасы",
      "shell.root.label": "Астананың қалалық платформасы",
      "common.nav.map": "Карта",
      "common.nav.day": "Күн қорытындысы",
      "common.nav.menu": "Мәзір",
      "common.nav.mine": "Менің өтініштерім",
      "common.action.skip_to_main": "Негізгі түймеге өту",
      "common.lang.label": "Интерфейс тілі",
      "common.lang.ru": "РУС",
      "common.lang.kk": "ҚАЗ",
      "common.role.label": "Кімнің көрінісі",
      "common.role.akimat": "Әкімдік",
      "common.role.resident": "Тұрғын",
      "proposal.catalog.title": "Не салайық?",
      "common.action.close": "Жабу",
      "common.action.retry": "Қайталау",
      "common.search.clear": "Іздеуді тазарту",
      "akim.title": "Күн қорытындысы",
      "shell.day.soon_title": "Күн қорытындысы жақында қосылады",
      "shell.day.soon_text": "Мұнда күн қорытындысы болады: өтініш тақырыптары, аудандар, шағымы көп орындар, мерзімі өткен және кестеден қалып жатқан нысандар.",
      "shell.day.back": "Картаға оралу",
      "shell.day.error_title": "Күн қорытындысы ашылмады",
      "shell.day.error_text": "Бір минуттан кейін қайталап көріңіз.",
      "shell.sheet.expand": "Панельді ашу",
      "shell.sheet.collapse": "Панельді жию",
      "shell.panel.eyebrow": "Астана · қалалық жұмыстар мен оқиғалар",
      "shell.panel.title": "Қалада не өзгеріп жатыр",
      "shell.panel.note": "Тек жарияланған жазбалар көрсетілген. Әр карточкада — дереккөз, мәлімет түрі және мерзімдер тарихы.",
      "shell.feedback.label": "Тұрғын хабарламасы",
      "shell.feedback.title": "Мәселе немесе ұсыныс туралы хабарлау",
      "shell.feedback.close": "Форманы жабу",
      "shell.assistant.label": "Нысан бойынша сұрақ",
      "shell.staff.open": "Қызметкерлерге",
      "shell.scenarios.open": "Шектеулерді салыстыру",
      "shell.moderation.open": "Тұрғындар хабарламалары",
      "shell.editor.title": "Қызметкер кабинеті",
      "shell.editor.close": "Кабинетті жабу",
      "shell.moderation.title": "Тұрғындар хабарламалары",
      "shell.moderation.close": "Хабарламаларды жабу",
      "shell.scenarios.title": "Шектеулерді салыстыру",
      "shell.scenarios.close": "Салыстыруды жабу",
      "shell.module.missing": "Бұл бөлік әзірге жүктелмеді. Бетті жаңартыңыз немесе кейінірек қайта кіріңіз.",
      "shell.module.failed": "Бұл бөлік іске қосылмады. Бетті жаңартыңыз немесе кейінірек қайта кіріңіз.",
      "shell.state.no_server": "Сервермен байланыс жоқ. Қосымшаның іске қосылғанын тексеріп, бетті жаңартыңыз.",
      "shell.state.no_store": "Жұмыстар туралы жазбалар қазір қолжетімсіз: карта әзірге бос.",
      "shell.feedback.unavailable": "Хабарлама жіберу қазір қолжетімсіз.",
      "shell.moderation.failed": "Хабарламалар тізімі ашылмады. Бетті жаңартыңыз.",
      "shell.tool.click_hint": "Картада құрал ашық тұрғанда, басу нысан карточкаларын ашпайды.",
      "shell.api.failed": "Сұрау орындалмады.",
      "shell.api.timeout": "Сервер уақытында жауап бермеді. Қайталап көріңіз.",
      "shell.api.network": "Қосымша серверімен байланыс жоқ.",
      "shell.api.bad_response": "Сервер оқылмайтын жауап қайтарды.",
      "shell.api.unauthenticated": "Жалғастыру үшін қызметкер ретінде кіріңіз.",
      "shell.view.city": "Шолу: бүкіл Астана",
      "shell.view.object": "Ашық жазба: {title}",
      "shell.view.object_untitled": "Жазба ашық",
      "shell.view.district": "{name} ауданы (OSM шекарасы)",
      "shell.view.street": "Көше: {name}",
      "shell.view.objects": "Картадағы барлық жарияланған жазбалар",
      "shell.view.registry_empty": "{label} · тізілім бос",
      "shell.view.in_frame": "{label} · кадрдағы жазбалар: {n}",
      "shell.view.none_in_frame": "{label} · кадрда жарияланған жазба жоқ (бұл жұмыс жоқ дегенді білдірмейді)",
      "shell.objects.none": "Тізілімде әзірге жарияланған жазба жоқ.",
      "shell.objects.no_coords": "Таңдалған сүзгілер бойынша координаталары бар нысан жоқ.",
      "shell.explore.label": "Астана бойынша навигация",
      "shell.explore.area": "Аумақ",
      "shell.explore.district_label": "Астана ауданы",
      "shell.explore.all_city": "Бүкіл Астана",
      "shell.explore.to_objects": "Нысандарға",
      "shell.explore.layers": "Қабаттар",
      "shell.explore.layers_label": "Картаның қамтуы мен қабаттары",
      "shell.explore.district_borders": "Аудан шекаралары",
      "shell.explore.coverage": "Карта бүкіл Астана бойынша қолжетімді. Бос орын жұмыс жоқ дегенді емес, жарияланған жазба жоқ дегенді білдіреді.",
      "shell.explore.borders_source": "Шекаралар: OpenStreetMap, 23.09.2026 жағдайы. Бұл қоғамдық карта, кадастрлық шекаралар емес.",
      "shell.explore.street_placeholder": "Астана көшесі",
      "shell.explore.street_label": "Астанадан көше іздеу",
      "shell.explore.find": "Табу",
      "shell.explore.streets_label": "Астана көшелері",
      "shell.explore.loading": "Көшелер тізімі жүктелуде…",
      "shell.explore.street_hint": "Көше атаулары OpenStreetMap деректерінен. Іздеу көшелер бойынша, үй нөмірлерінсіз.",
      "shell.explore.street_hint_date": "Көше атаулары OpenStreetMap деректерінен, {date} жағдайы. Іздеу көшелер бойынша, үй нөмірлерінсіз.",
      "shell.explore.index_error": "Көше іздеу қолжетімсіз: көшелер тізімі жүктелмеді. Ауданды таңдаңыз немесе қайталаңыз.",
      "shell.explore.pin_title": "Шамамен орын: OpenStreetMap бойынша көше бөлігінің ортасы",
      "shell.explore.more": "Тағы {n} — атауын нақтылаңыз",
      "shell.explore.not_found": "Көше OpenStreetMap деректерінен табылмады. Жазылуын тексеріңіз немесе ауданды таңдаңыз.",
      "shell.explore.found_ambiguous": "Табылған нұсқалар: {n}. Аттас көшелердің жанында аудан көрсетілген.",
      "shell.explore.found_pick": "Табылған нұсқалар: {n}. Көрсеткілер мен Enter арқылы немесе түртіп таңдаңыз.",
      "shell.explore.chosen": "Көрсетілген көше: {name} ({place}). Жазбалар тізімі — картаның көрінетін бөлігі бойынша.",
      "shell.explore.count": "Жарияланған жазбалар: {n}. Оның ішінде үлгілер: {demo}.",
      "shell.explore.registry_empty": "Тізілім бос: әзірге жарияланған жазба жоқ. Бос карта қалада жұмыс жоқ дегенді білдірмейді.",
      "district.name": "{name} ауданы",
      "district.esil": "Есіл",
      "district.almaty": "Алматы",
      "district.saryarka": "Сарыарқа",
      "district.baikonur": "Байқоңыр",
      "district.nura": "Нұра",
      "district.saraishyk": "Сарайшық",
      "shell.explore.place_outside": "маңы, аудан шекарасынан тыс",
      "shell.explore.place_part": "{place} · бөлік {i}/{n}",
    },
  };

  // Подстановка {name}; числа — с неразрывным пробелом между тысячами («1 666»), как в i18n R11.
  function fill(text, params) {
    if (!params) return text;
    return String(text).replace(/\{(\w+)\}/g, (whole, name) => {
      if (!Object.prototype.hasOwnProperty.call(params, name) || params[name] == null) return whole;
      const v = params[name];
      return typeof v === "number" ? String(v).replace(/\B(?=(\d{3})+(?!\d))/g, " ") : String(v);
    });
  }
  // Текст по ключу без словарей R11 (Node, тесты, запасной путь).
  function text(key, params, lang) {
    const l = lang === "kk" ? "kk" : "ru";
    const value = (TEXT[l] && TEXT[l][key]) || TEXT.ru[key];
    return value === undefined ? key : fill(value, params);
  }
  const api = { TEXT, fill, text };
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.BirgeShellText = api;
})(typeof self !== "undefined" ? self : this);
