"""Build research/round-11-results/R10/EVIDENCE_INDEX.json from the files actually present.

  python3 -I -B tests/civic/R10/build_evidence_index.py

Every run, screenshot and document is listed with sha256, so a reader can check that a claim
in VERDICT.json points at a real file of this commit. Summaries are read from the run JSON,
never typed by hand.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
RESULTS = REPO / "research" / "round-11-results" / "R10"


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def rel(path: Path) -> str:
    return str(path.relative_to(REPO))


def main():
    runs = []
    for p in sorted((RESULTS / "runs").glob("*.json")):
        d = json.loads(p.read_text(encoding="utf-8"))
        entry = {"path": rel(p), "sha256": sha(p), "label": d.get("label")}
        if "counts" in d:
            tgt = d.get("target") or {}
            entry.update(kind="suite", started_utc=d.get("started_utc"), counts=d["counts"],
                         code_sha=tgt.get("code_sha"), target=tgt.get("target"), mutant=tgt.get("mutant"),
                         code_roots={k: v.get("sha") for k, v in (d.get("code_roots") or {}).items()},
                         acceptance={k: v["status"] for k, v in (d.get("acceptance") or {}).items()})
        elif "checks" in d and isinstance(d["checks"], list):
            entry.update(kind="checks", code_sha=(d.get("target") or {}).get("code_sha") or d.get("code_sha"),
                         checks={c.get("id"): c.get("status") for c in d["checks"] if isinstance(c, dict)})
        elif "steps" in d:
            statuses = [s.get("status") for s in d["steps"]]
            entry.update(kind="browser", code_sha=d.get("code_sha"),
                         counts={s: statuses.count(s) for s in sorted(set(map(str, statuses)))})
        runs.append(entry)
    shots = [{"path": rel(p), "sha256": sha(p), "bytes": p.stat().st_size}
             for p in sorted((RESULTS / "shots").rglob("*.png"))]
    docs = [{"path": rel(p), "sha256": sha(p)} for p in sorted(RESULTS.glob("*"))
            if p.is_file() and p.name != "EVIDENCE_INDEX.json"]
    patches = [{"path": rel(p), "sha256": sha(p)} for p in sorted((RESULTS / "patches").glob("*"))]
    tests = [{"path": rel(p), "sha256": sha(p)} for p in sorted(HERE.rglob("*"))
             if p.is_file() and "__pycache__" not in p.parts and p.suffix in (".py", ".cjs", ".json", ".md")]
    index = {
        "round": 11, "role": "R10",
        "generated_utc": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "note": "Generated by tests/civic/R10/build_evidence_index.py from files present in this commit.",
        "runs": runs, "screenshots": shots, "documents": docs, "patches": patches, "tests": tests,
    }
    out = RESULTS / "EVIDENCE_INDEX.json"
    out.write_text(json.dumps(index, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"{len(runs)} runs, {len(shots)} screenshots, {len(docs)} documents, {len(tests)} test files -> {rel(out)}")


if __name__ == "__main__":
    main()
