/* Stage 2: facts catalog + verified explanation for the city-evidence demo.
 * Port of K02 verified_explainer (claude/clever-mccarthy-pywscu @ 24c1750): catalog -> selector (IDs only)
 * -> validate_plan -> render. Text equality with the Python original is checked by tests/conformance.cjs
 * against tests/expected_explanations.json (generated by tools/explain_ref.py with the unmodified K02 module).
 * District status per record comes from K03 assign() (precomputed in evidence.js); numbers are K05 observations.
 * The selector is a deterministic stub, not an LLM; its output is labelled as a template explanation.
 * Works in the browser (window.CITY_FACTS) and in Node (module.exports) for tests.
 */
(function (root) {
  "use strict";
  const GROUP_ORDER = ["school", "preschool", "college_university", "hospital", "outpatient_clinic", "pharmacy", "government_office"];
  const ID_PATTERN = /^([a-z][a-z_]*)\/([A-Za-z0-9_]+)\/([a-z][a-z0-9_.]*)$/;
  const SECTION_TYPES = ["summary", "weakest", "risks", "data_gaps"];
  const MAX_FACTS = 6, MAX_SECTIONS = 4;
  const STUB_NAME = "шаблонное объяснение (детерминированная заглушка, не LLM)";
  const TEXT = {
    header: { ru: "Проверяемая часть (значения из каталога фактов среза)", kk: "Тексерілетін бөлік (мәндер кесінді деректер каталогынан)" },
    scenario: { ru: "Срез", kk: "Кесінді" },
    summary: { ru: "Итог", kk: "Қорытынды" }, weakest: { ru: "Самый слабый район", kk: "Ең әлсіз аудан" },
    risks: { ru: "Риски", kk: "Тәуекелдер" }, data_gaps: { ru: "Нет данных", kk: "Дерек жоқ" },
    unknown: { ru: "нет данных", kk: "дерек жоқ" },
    kind_model: { ru: "учебная модель", kk: "оқу моделі" }, kind_observed: { ru: "наблюдение", kk: "бақылау" },
    kind_derived: { ru: "расчёт", kk: "есептелген" }, kind_synthetic: { ru: "синтетика", kk: "синтетикалық" },
    kind_unknown: { ru: "неизвестно", kk: "белгісіз" },
  };
  const KINDS = new Set(["observed", "derived", "model", "synthetic", "unknown"]);
  const FIXED_LABELS = {
    "places.selected": ["Записей выбранных категорий в квадрате", "Таңдалған санаттар жазбалары шаршыда"],
    "district_status.matched": ["Записей с проверенной привязкой к району", "Ауданға сенімді байланған жазбалар"],
    "district_status.ambiguous": ["Записей с неоднозначным районом", "Ауданы анық емес жазбалар"],
    "district_status.unmatched": ["Записей внутри города вне районов", "Қала ішінде, ауданнан тыс жазбалар"],
    "segments.foot_unknown": ["Сегментов дорог без данных о проходе пешком", "Жаяу өту дерегі жоқ жол сегменттері"],
    "capacity.school_places": ["Мощность школ (места)", "Мектептер сыйымдылығы (орын)"],
    "registry.official_schools": ["Официальный реестр школ", "Мектептердің ресми тізілімі"],
    "population.children": ["Число детей", "Балалар саны"],
  };

  class PlanError extends Error {
    constructor(code, detail) { super(code + ": " + detail); this.code = code; this.detail = detail; }
  }

  // agent.evidence.format_value: integers as is; decimal point -> comma; strings escaped.
  function formatValue(v) {
    if (typeof v === "string") return v.replace(/([\\`*_{}\[\]()<>#!|])/g, "\\$1");
    if (typeof v !== "number" || !isFinite(v)) throw new Error("format_value: not a finite number");
    return String(v).replace(".", ",");
  }

  function scenarioId(sliceId, groups) {
    let mask = 0;
    GROUP_ORDER.forEach((g, i) => { if (groups.has(g)) mask |= 1 << i; });
    return `${sliceId}_g${mask}`;
  }

  function labels(path, data, ev) {
    const g = path.startsWith("places.") ? path.slice(7) : null;
    if (g && data.groups[g]) return [data.groups[g].label + ": записей в квадрате", ev.group_kk[g] + ": шаршыдағы жазбалар"];
    if (!FIXED_LABELS[path]) throw new Error("no label for " + path);
    return FIXED_LABELS[path];
  }

  // Catalog of the current city / category filter / slice (same rows as tools/explain_ref.py catalog_rows).
  function buildCatalog(data, ev, city, groups) {
    const c = data.cities[city], e = ev.cities[city];
    if (!c || !e) throw new PlanError("foreign_city", `нет данных для города ${city}`);
    const period = scenarioId(ev.slice_id, groups), obs = {};
    for (const o of e.observations) obs[o.indicator_id] = o;
    const sel = c.places.filter((p) => groups.has(p.group));
    const cat = new Map();
    const add = (path, value, kind, source) => {
      const fid = `${city}/${period}/${path}`, m = ID_PATTERN.exec(fid);
      if (!m || m[1] !== city || m[2] !== period) throw new Error("bad fact id " + fid);
      const k = value === null || value === undefined ? "unknown" : kind;
      if (!KINDS.has(k)) throw new Error("unknown kind " + k);
      const [ru, kk] = labels(path, data, ev);
      cat.set(fid, { id: fid, city, scenario: period, kind: k, value: value === undefined ? null : value, label: { ru, kk }, source });
    };
    add("places.selected", sel.length, "derived", "data.js: число записей выбранных категорий");
    for (const g of GROUP_ORDER) if (groups.has(g)) { const o = obs["places." + g]; add("places." + g, o.value, o.kind, "k05:" + o.obs_id); }
    const st = {};
    for (const p of sel) { const s = (e.place_district[p.id] || { status: "unknown" }).status; st[s] = (st[s] || 0) + 1; }
    for (const s of ["matched", "ambiguous", "unmatched"]) add("district_status." + s, st[s] || 0, "derived", "K03 k03_assign_v1 по записям фильтра");
    const fu = obs["segments.foot_unknown"]; add("segments.foot_unknown", fu.value, fu.kind, "k05:" + fu.obs_id);
    for (const ind of ["capacity.school_places", "registry.official_schools", "population.children"]) { const o = obs[ind]; add(ind, o.value, o.kind, "k05:" + o.obs_id); }
    return { catalog: cat, scenario: period, city };
  }

  function catalogView(cat) {
    return [...cat.values()].map((f) => ({ id: f.id, label_ru: f.label.ru, kind: f.kind, has_value: f.value !== null }));
  }

  const StubSelector = {
    name: STUB_NAME,
    select(view) {
      const ends = (v, ...s) => s.some((x) => v.id.endsWith("/" + x));
      const summary = view.filter((v) => v.has_value && v.id.includes("/places.")).map((v) => v.id).slice(0, MAX_FACTS);
      const risks = view.filter((v) => v.has_value && ends(v, "district_status.ambiguous", "district_status.unmatched", "segments.foot_unknown")).map((v) => v.id);
      const gaps = view.filter((v) => !v.has_value).map((v) => v.id).slice(0, MAX_FACTS);
      const sections = [{ type: "summary", fact_ids: summary }, { type: "risks", fact_ids: risks }, { type: "data_gaps", fact_ids: gaps }];
      return { sections: sections.filter((s) => s.fact_ids.length), comment: null };
    },
  };

  // validate_plan (K02): shape, section types, ID syntax, city, scenario, catalog membership, null only in data_gaps.
  function validatePlan(plan, cat, city, scenario, knownIds) {
    if (!plan || typeof plan !== "object" || Array.isArray(plan) || !("sections" in plan) || Object.keys(plan).some((k) => k !== "sections" && k !== "comment"))
      throw new PlanError("bad_shape", "ожидается объект {sections, comment?}");
    const secs = plan.sections;
    if (!Array.isArray(secs) || !secs.length || secs.length > MAX_SECTIONS) throw new PlanError("bad_shape", `нужно 1–${MAX_SECTIONS} секций`);
    const seen = new Set(), out = [];
    for (const s of secs) {
      if (!s || typeof s !== "object" || Object.keys(s).sort().join() !== "fact_ids,type") throw new PlanError("bad_shape", "секция = {type, fact_ids}");
      if (!SECTION_TYPES.includes(s.type)) throw new PlanError("bad_section", `тип секции ${s.type} не разрешён`);
      if (seen.has(s.type)) throw new PlanError("bad_section", `секция ${s.type} повторяется`);
      seen.add(s.type);
      if (!Array.isArray(s.fact_ids) || !s.fact_ids.length || s.fact_ids.length > MAX_FACTS) throw new PlanError("bad_shape", `в секции 1–${MAX_FACTS} ID`);
      for (const fid of s.fact_ids) {
        if (typeof fid !== "string") throw new PlanError("not_an_id", `${fid} не строка`);
        const m = ID_PATTERN.exec(fid);
        if (!m) throw new PlanError("not_an_id", `${fid.slice(0, 60)} не является ID факта`);
        if (m[1] !== city) throw new PlanError("foreign_city", `${fid}: город ${m[1]}, запрос по ${city}`);
        if (m[2] !== scenario) throw new PlanError("stale_scenario", `${fid}: срез ${m[2]}, текущий ${scenario}`);
        if (!cat.has(fid)) throw new PlanError("unknown_id", `${fid} нет в каталоге текущего среза` + (knownIds && knownIds.has(fid) ? " (известен системе)" : ""));
        const f = cat.get(fid);
        if (f.value === null && s.type !== "data_gaps") throw new PlanError("null_as_fact", `${fid} не имеет значения; его место только в data_gaps`);
        if (f.value !== null && s.type === "data_gaps") throw new PlanError("value_in_gaps", `${fid} имеет значение, а секция data_gaps для неизвестных`);
      }
      if (new Set(s.fact_ids).size !== s.fact_ids.length) throw new PlanError("duplicate_id", "ID в секции повторяется");
      out.push({ type: s.type, fact_ids: s.fact_ids.slice() });
    }
    if (plan.comment !== undefined && plan.comment !== null && typeof plan.comment !== "string") throw new PlanError("bad_shape", "comment — строка или null");
    return { sections: out, comment: plan.comment ?? null };
  }

  function render(plan, cat, scenario, lang) {
    if (lang !== "ru" && lang !== "kk") throw new Error("lang: ru | kk");
    const lines = [`**${TEXT.header[lang]}.** ${TEXT.scenario[lang]}: ${scenario}.`], used = [];
    for (const s of plan.sections) {
      lines.push(`\n**${TEXT[s.type][lang]}**`);
      for (const fid of s.fact_ids) {
        const f = cat.get(fid);
        const val = f.value === null ? TEXT.unknown[lang] : formatValue(f.value);
        lines.push(`- ${f.label[lang]}: ${val} (${TEXT["kind_" + f.kind][lang]})`);
        used.push({ id: fid, value: f.value, kind: f.kind, source: f.source });
      }
    }
    return { text: lines.join("\n"), facts_used: used };  // comments are dropped (K02 comment_policy="drop")
  }

  function explain(data, ev, city, groups, lang, selector) {
    const { catalog, scenario } = buildCatalog(data, ev, city, groups);
    const plan = (selector || StubSelector).select(catalogView(catalog));
    const accepted = validatePlan(plan, catalog, city, scenario);
    return { ...render(accepted, catalog, scenario, lang), scenario, selector: (selector || StubSelector).name };
  }

  // ---------- UI glue (browser only) ----------
  const STATUS_RU = { matched: "проверенная привязка", ambiguous: "неоднозначно", unmatched: "в городе, вне районов", outside: "вне города", invalid: "ошибка координат" };
  function districtOf(city, place) {
    const ev = root.CITY_OBS, rec = ev && ev.cities[city] && ev.cities[city].place_district[place.id];
    if (!rec) return { text: "не определён", badge: "нет привязки" };
    if (rec.status === "matched") {
      const n = ev.district_names[rec.district] || {};
      return { text: n.kk && n.ru && n.kk !== n.ru ? `${n.ru} / ${n.kk}` : (n.ru || n.kk || rec.district), badge: "K03 · OSM, не официально" };
    }
    return { text: `не присвоен (${STATUS_RU[rec.status] || rec.status})`, badge: rec.candidates.length ? "кандидаты: " + rec.candidates.join(", ") : "K03" };
  }

  function provenanceNotes(city) {
    const ev = root.CITY_OBS;
    if (!ev || !ev.cities[city]) return ["Каталог фактов не загружен (evidence.js)."];
    const e = ev.cities[city];
    return [`Привязка к районам: правило ${ev.assign_rule} (K03), границы OSM/Overture, юридический статус не проверен.`,
      `Наблюдения проверены контрактом k05-obs-v1.1 (K05): ${e.observations.length} записей, ошибок 0, предупреждения: ${[...new Set(e.validation.flatMap((v) => v.warnings.map((w) => w.split(":")[0])))].join(", ") || "нет"}.`,
      "Районные суммы E02/E03 раунда 2 сюда не переносились: K08 нашёл в E03 двойной счёт дорог на общих границах."];
  }

  function renderExplanation(body, ctx) {
    const { state, data, isCurrent, el } = ctx;
    const ev = root.CITY_OBS;
    body.replaceChildren();
    if (!ev || !ev.cities || !ev.cities[state.city]) {
      body.append(el("p", { class: "err" }, "Каталог фактов недоступен: нет web/evidence.js. Соберите: tools/build_evidence.py."));
      return;
    }
    const groups = state.places ? state.groups : new Set();
    let built;
    try { built = buildCatalog(data, ev, state.city, groups); } catch (e) { body.append(el("p", { class: "err" }, "Ошибка каталога: " + e.message)); return; }
    const tbl = el("table", { class: "facts" }), tb = el("tbody");
    for (const f of built.catalog.values()) {
      const tr = el("tr");
      tr.append(el("td", { class: "k" }, f.label.ru),
        el("td", { class: "num" + (f.value === null ? " kv-unknown" : "") }, f.value === null ? "нет данных" : formatValue(f.value)),
        el("td", null, TEXT["kind_" + f.kind].ru));
      tb.append(tr);
    }
    tbl.append(tb);
    const det = el("details"); det.append(el("summary", null, `Каталог фактов (${built.catalog.size}) · срез ${built.scenario}`), tbl);
    body.append(det, el("p", { class: "muted" }, "«нет данных» — значение неизвестно, а не 0. Ноль показан только там, где он посчитан по всем записям среза."));
    const lang = state.lang || "ru";
    const row = el("div", { class: "ctl" });
    const btn = el("button", { class: "tool", type: "button" }, "Объяснить срез");
    const langSel = el("select", { "aria-label": "Язык объяснения" });
    for (const [v, t] of [["ru", "русский"], ["kk", "қазақша (черновик)"]]) { const o = el("option", { value: v }, t); if (v === lang) o.selected = true; langSel.append(o); }
    langSel.addEventListener("change", () => { state.lang = langSel.value; });
    row.append(btn, langSel);
    const outBox = el("div", { class: "explain", hidden: "" });
    body.append(row, outBox);
    btn.addEventListener("click", () => {
      btn.disabled = true;
      // Async like a future provider call: a reply that arrives after a city/filter change is discarded.
      Promise.resolve().then(() => StubSelector.select(catalogView(built.catalog))).then((plan) => {
        if (!isCurrent()) return;  // stale reply: city or filter changed meanwhile
        btn.disabled = false;
        outBox.hidden = false; outBox.replaceChildren();
        try {
          const cur = buildCatalog(data, ev, state.city, state.places ? state.groups : new Set());
          const accepted = validatePlan(plan, cur.catalog, state.city, cur.scenario);
          const r = render(accepted, cur.catalog, cur.scenario, state.lang || "ru");
          outBox.append(el("div", { class: "who" }, STUB_NAME + ". Модель не вызывалась; текст собран кодом из фактов."));
          for (const line of r.text.split("\n")) {
            if (!line.trim()) continue;
            const m = /^\*\*(.+?)\*\*(.*)$/.exec(line.trim());
            if (m) { const p = el("p"); p.append(el("strong", null, m[1]), document.createTextNode(m[2])); outBox.append(p); }
            else outBox.append(el("div", null, line.replace(/^- /, "• ")));
          }
        } catch (e) {
          outBox.append(el("p", { class: "err" }, `План отклонён (${e.code || "error"}): ${e.detail || e.message}`));
        }
      });
    });
  }

  const api = { GROUP_ORDER, PlanError, formatValue, scenarioId, buildCatalog, catalogView, StubSelector, validatePlan, render, explain,
    districtOf, provenanceNotes, renderExplanation };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.CITY_FACTS = api;
})(typeof window !== "undefined" ? window : globalThis);
