/*
 * R09 · тексты пути жителя и «Моих обращений» (ru / kk).
 * Это ЗАПАСНОЙ словарь: если подключён web/civic/i18n/i18n.js (R11) и в нём есть ключ,
 * берётся перевод R11. Ключи и черновики переводов передаются R11 в INTEGRATION.txt;
 * после того как R11 перенесёт их в ru.json / kk.json, этот файл можно не подключать.
 * Значения выровнены со словарём R11 (claude/r14-R11 @ 52d7c59, ночь раунда 14): при расхождении прав R11.
 * Формы чисел ru: {one, few, many}; в kk существительное после числа не меняется — одна строка.
 */
(function () {
  "use strict";
  window.BirgeComplaintStrings = {
    ru: {
      "complaint.start.button": "Сообщить о проблеме",
      "complaint.wizard.step": "Шаг {n} из {total}",
      "complaint.wizard.back": "Назад",
      "complaint.wizard.close": "Закрыть",
      "complaint.wizard.next": "Далее",

      "complaint.step2.title": "Где проблема?",
      "complaint.step2.hint": "Нажмите на карту или определите ваше место",
      "complaint.step2.locate": "Моё местоположение",
      "complaint.step2.locating": "Определяем ваше место…",
      "complaint.step2.locate_failed": "Не удалось определить место. Нажмите на карту.",
      "complaint.step2.loading": "Ищем, что рядом…",
      "complaint.step2.question": "Это здесь?",
      "complaint.step2.choose": "Выберите, о чём жалоба",
      "complaint.step2.distance": "{n} м",
      "complaint.step2.here": "Вы здесь",
      "complaint.step2.other_place": "Другое место",
      "complaint.step2.approximate": "Примерное место",
      "complaint.step2.approximate_hint": "Отметим область около точки. Акимат уточнит место.",
      "complaint.step2.selected": "Выбрано: {label}",
      "complaint.step2.pick_again": "Нажмите на карту, чтобы выбрать другую точку.",

      "complaint.step3.title": "Что случилось?",
      "complaint.step3.label": "Опишите проблему",
      "complaint.step3.example": "Например: «{example}»",
      "complaint.step3.privacy": "Не пишите телефон и ИИН: текст увидят только сотрудники акимата.",
      "complaint.step3.too_short": "Опишите проблему хотя бы в нескольких словах",
      "complaint.step3.suggested": "Похоже на:",
      "complaint.step3.change": "Сменить категорию",
      "complaint.step3.choose": "Выберите категорию",
      "complaint.step3.chosen": "Категория:",
      "complaint.step3.send": "Отправить",
      "complaint.step3.sending": "Отправляем…",

      "complaint.step4.title": { "one": "Об этом уже сообщил {n} человек", "few": "Об этом уже сообщили {n} человека", "many": "Об этом уже сообщили {n} человек" },
      "complaint.step4.hint": "Нажмите «Я тоже» — так жалоба станет весомее и не потеряется среди повторов",
      "complaint.step4.ago_days": { "one": "{n} день назад", "few": "{n} дня назад", "many": "{n} дней назад" },
      "complaint.step4.today": "сегодня",
      "complaint.step4.metoo": "Я тоже",
      "complaint.step4.different": "У меня другое",

      "complaint.step5.title": "Обращение отправлено",
      "complaint.step5.metoo_title": "Ваш голос учтён",
      "complaint.step5.metoo_count": { "one": "Теперь сообщил {n} человек", "few": "Теперь сообщили {n} человека", "many": "Теперь сообщили {n} человек" },
      "complaint.step5.already": "Вы уже нажимали «Я тоже» для этой проблемы.",
      "complaint.step5.author": "Это ваше обращение — вы уже в числе сообщивших.",
      "complaint.step5.code_label": "Номер обращения:",
      "complaint.step5.copy": "Скопировать",
      "complaint.step5.copied": "Номер скопирован",
      "complaint.step5.due": "Ответ до {date}",
      "complaint.step5.mine": "Мои обращения",
      "complaint.step5.to_map": "На карту",

      "complaint.error.send": "Не удалось отправить. Проверьте связь и повторите.",
      "complaint.error.retry": "Повторить",
      "complaint.error.too_many": "Слишком много обращений подряд. Повторите позже.",
      "complaint.error.outside": "Это место вне Астаны. Выберите точку в городе.",

      "mine.title": "Мои обращения",
      "mine.count": "Мои обращения ({n})",
      "mine.loading": "Загружаем обращения…",
      "mine.empty.title": "Вы ещё ничего не отправляли",
      "mine.empty.hint": "Сообщите о проблеме — здесь появится её статус.",
      "mine.error.title": "Нет связи с сервером",
      "mine.error.hint": "Проверьте интернет и повторите.",
      "mine.metoo_badge": "Вы нажали «Я тоже»",
      "mine.reporters": { "one": "Сообщил {n} человек", "few": "Сообщили {n} человека", "many": "Сообщили {n} человек" },
      "mine.overdue": "Срок ответа прошёл",

      "status.new": "Новое",
      "status.accepted": "Принято",
      "status.in_progress": "В работе",
      "status.fixed": "Исправлено",
      "status.rejected": "Отклонено",
      "common.demo": "Пример",
      "common.lang.ru": "РУС",
      "common.lang.kk": "ҚАЗ",

      "complaint.example.roads": "Яма на дороге у остановки",
      "complaint.example.snow_ice": "Не убран снег, скользко на переходе",
      "complaint.example.sidewalks": "Разбит тротуар у школы",
      "complaint.example.transport": "У остановки сломан павильон",
      "complaint.example.lighting": "Во дворе не горят фонари",
      "complaint.example.yards": "Сломана детская площадка",
      "complaint.example.waste": "Баки переполнены третий день",
      "complaint.example.utilities": "В доме нет горячей воды",
      "complaint.example.smell_air": "Сильный запах гари по вечерам",
      "complaint.example.noise_safety": "Нет пешеходного перехода у школы",
      "complaint.example.parking": "Машины стоят на газоне во дворе",
      "complaint.example.other": "Опишите своими словами"
    },
    kk: {
      "complaint.start.button": "Мәселе туралы хабарлау",
      "complaint.wizard.step": "Қадам {n}/{total}",
      "complaint.wizard.back": "Артқа",
      "complaint.wizard.close": "Жабу",
      "complaint.wizard.next": "Әрі қарай",

      "complaint.step2.title": "Мәселе қай жерде?",
      "complaint.step2.hint": "Картаны басыңыз немесе орныңызды анықтаңыз",
      "complaint.step2.locate": "Менің орным",
      "complaint.step2.locating": "Орныңыз анықталып жатыр…",
      "complaint.step2.locate_failed": "Орынды анықтау мүмкін болмады. Картаны басыңыз.",
      "complaint.step2.loading": "Маңайдағы нысандарды іздеп жатырмыз…",
      "complaint.step2.question": "Осы жерде ме?",
      "complaint.step2.choose": "Шағым неге қатысты екенін таңдаңыз",
      "complaint.step2.distance": "{n} м",
      "complaint.step2.here": "Сіз осындасыз",
      "complaint.step2.other_place": "Басқа орын",
      "complaint.step2.approximate": "Шамамен көрсетілген орын",
      "complaint.step2.approximate_hint": "Нүктенің маңайындағы аумақты белгілейміз. Әкімдік орнын нақтылайды.",
      "complaint.step2.selected": "Таңдалды: {label}",
      "complaint.step2.pick_again": "Басқа нүктені таңдау үшін картаны басыңыз.",

      "complaint.step3.title": "Не болды?",
      "complaint.step3.label": "Мәселені сипаттаңыз",
      "complaint.step3.example": "Мысалы: «{example}»",
      "complaint.step3.privacy": "Телефон мен ЖСН жазбаңыз: мәтінді тек әкімдік қызметкерлері көреді.",
      "complaint.step3.too_short": "Мәселені бірнеше сөзбен болса да сипаттаңыз",
      "complaint.step3.suggested": "Ұқсас санат:",
      "complaint.step3.change": "Санатты өзгерту",
      "complaint.step3.choose": "Санатты таңдаңыз",
      "complaint.step3.chosen": "Санат:",
      "complaint.step3.send": "Жіберу",
      "complaint.step3.sending": "Жіберілуде…",

      "complaint.step4.title": "Бұл туралы {n} адам хабарлаған",
      "complaint.step4.hint": "«Мен де» деп белгілесеңіз, шағым күштірек болады және қайталанбайды",
      "complaint.step4.ago_days": "{n} күн бұрын",
      "complaint.step4.today": "бүгін",
      "complaint.step4.metoo": "Мен де",
      "complaint.step4.different": "Менде басқа мәселе",

      "complaint.step5.title": "Өтініш жіберілді",
      "complaint.step5.metoo_title": "Сіздің дауысыңыз есепке алынды",
      "complaint.step5.metoo_count": "Енді {n} адам хабарлады",
      "complaint.step5.already": "Сіз бұл мәселе бойынша «Мен де» түймесін бұрын басқансыз.",
      "complaint.step5.author": "Бұл — сіздің өтінішіңіз, сіз хабарлағандардың қатарындасыз.",
      "complaint.step5.code_label": "Өтініш нөмірі:",
      "complaint.step5.copy": "Көшіру",
      "complaint.step5.copied": "Нөмір көшірілді",
      "complaint.step5.due": "Жауап мерзімі: {date}",
      "complaint.step5.mine": "Менің өтініштерім",
      "complaint.step5.to_map": "Картаға",

      "complaint.error.send": "Жіберу мүмкін болмады. Байланысты тексеріп, қайталаңыз.",
      "complaint.error.retry": "Қайталау",
      "complaint.error.too_many": "Қатарынан тым көп өтініш жіберілді. Кейінірек қайталаңыз.",
      "complaint.error.outside": "Бұл орын Астанадан тыс. Қаладағы нүктені таңдаңыз.",

      "mine.title": "Менің өтініштерім",
      "mine.count": "Менің өтініштерім ({n})",
      "mine.loading": "Өтініштер жүктелуде…",
      "mine.empty.title": "Сіз әлі ештеңе жібермедіңіз",
      "mine.empty.hint": "Мәселе туралы хабарлаңыз — оның мәртебесі осында шығады.",
      "mine.error.title": "Сервермен байланыс жоқ",
      "mine.error.hint": "Интернетті тексеріп, қайталаңыз.",
      "mine.metoo_badge": "Сіз «Мен де» түймесін бастыңыз",
      "mine.reporters": "{n} адам хабарлады",
      "mine.overdue": "Жауап беру мерзімі өтті",

      "status.new": "Жаңа",
      "status.accepted": "Қабылданды",
      "status.in_progress": "Орындалуда",
      "status.fixed": "Түзетілді",
      "status.rejected": "Қабылданбады",
      "common.demo": "Үлгі",
      "common.lang.ru": "РУС",
      "common.lang.kk": "ҚАЗ",

      "complaint.example.roads": "Аялдама жанындағы жолда шұңқыр бар",
      "complaint.example.snow_ice": "Қар тазаланбаған, өткелде тайғақ",
      "complaint.example.sidewalks": "Мектеп жанындағы тротуар бұзылған",
      "complaint.example.transport": "Аялдаманың павильоны сынған",
      "complaint.example.lighting": "Аулада шамдар жанбайды",
      "complaint.example.yards": "Балалар алаңы сынған",
      "complaint.example.waste": "Қоқыс жәшіктері үш күннен бері толы",
      "complaint.example.utilities": "Үйде ыстық су жоқ",
      "complaint.example.smell_air": "Кешке қатты күйік иісі шығады",
      "complaint.example.noise_safety": "Мектеп жанында жаяу жүргіншілер өткелі жоқ",
      "complaint.example.parking": "Аулада көліктер көгалда тұрады",
      "complaint.example.other": "Өз сөзіңізбен сипаттаңыз"
    }
  };
})();
